name: Maven CI workflow

on: push

jobs:
  maven_ci:
    name: Maven CI job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Maven
        run: mvn -B verify

